"""Create isolated TLR snapshot, evidence and link tables."""

import sqlalchemy as sa
from alembic import op

revision = "20260905_0002"
down_revision = "20260722_0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tlr_datasets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tlr_datasets_project_id"), "tlr_datasets", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_tlr_datasets_tenant_id"), "tlr_datasets", ["tenant_id"], unique=False)
    op.create_table(
        "tlr_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.String(length=128), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["tlr_datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "external_id"),
    )
    op.create_index(
        op.f("ix_tlr_artifacts_dataset_id"), "tlr_artifacts", ["dataset_id"], unique=False
    )
    op.create_table(
        "tlr_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','running','completed','failed')", name="ck_tlr_run_status"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["tlr_datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tlr_runs_dataset_id"), "tlr_runs", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_tlr_runs_project_id"), "tlr_runs", ["project_id"], unique=False)
    op.create_index(op.f("ix_tlr_runs_tenant_id"), "tlr_runs", ["tenant_id"], unique=False)
    op.create_table(
        "tlr_elements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("start", sa.Integer(), nullable=False),
        sa.Column("end", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["tlr_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["tlr_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "artifact_id", "role", "ordinal"),
    )
    op.create_index(op.f("ix_tlr_elements_run_id"), "tlr_elements", ["run_id"], unique=False)
    op.create_table(
        "tlr_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("gold_links", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["tlr_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tlr_evaluations_run_id"), "tlr_evaluations", ["run_id"], unique=False)
    op.create_table(
        "tlr_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("target_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("evidence_candidate_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["tlr_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["tlr_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_artifact_id"],
            ["tlr_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_artifact_id", "target_artifact_id"),
    )
    op.create_index(op.f("ix_tlr_links_run_id"), "tlr_links", ["run_id"], unique=False)
    op.create_table(
        "tlr_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("source_element_id", sa.String(length=36), nullable=False),
        sa.Column("target_element_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.CheckConstraint("decision IN ('pending','related','unrelated')", name="ck_tlr_decision"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["tlr_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_element_id"],
            ["tlr_elements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_element_id"],
            ["tlr_elements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_element_id", "target_element_id"),
    )
    op.create_index(op.f("ix_tlr_candidates_run_id"), "tlr_candidates", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tlr_candidates_run_id"), table_name="tlr_candidates")
    op.drop_table("tlr_candidates")
    op.drop_index(op.f("ix_tlr_links_run_id"), table_name="tlr_links")
    op.drop_table("tlr_links")
    op.drop_index(op.f("ix_tlr_evaluations_run_id"), table_name="tlr_evaluations")
    op.drop_table("tlr_evaluations")
    op.drop_index(op.f("ix_tlr_elements_run_id"), table_name="tlr_elements")
    op.drop_table("tlr_elements")
    op.drop_index(op.f("ix_tlr_runs_tenant_id"), table_name="tlr_runs")
    op.drop_index(op.f("ix_tlr_runs_project_id"), table_name="tlr_runs")
    op.drop_index(op.f("ix_tlr_runs_dataset_id"), table_name="tlr_runs")
    op.drop_table("tlr_runs")
    op.drop_index(op.f("ix_tlr_artifacts_dataset_id"), table_name="tlr_artifacts")
    op.drop_table("tlr_artifacts")
    op.drop_index(op.f("ix_tlr_datasets_tenant_id"), table_name="tlr_datasets")
    op.drop_index(op.f("ix_tlr_datasets_project_id"), table_name="tlr_datasets")
    op.drop_table("tlr_datasets")
    # ### end Alembic commands ###
